Update models.py
The original code was giving me the following error: Django - TypeError - save() got an unexpected keyword argument 'force_insert'

When you are overriding model's save method in Django, it appears we need to pass *args and **kwargs to overridden method.